name: Android CI

on:
  push:
    branches: [ main ]
  # Build on all pull requests, regardless of target.
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Build with Gradle
      run: ./gradlew build
